### ISSUE TITLE
Refactor overhaul

### ISSUE THREAD

**Issue by nebbles** [nebbles/gitcommit#41]
A major overhaul is needed. Currently the approach is functional, but already it is getting messy and the need for globals is pressing. Moving to a class based system could be a way out. Or a major revamp of the functional approach is necessary.

Important changes needed as part of this rework:
- [ ] Revamp functional or move to class based approach
- [ ] Test written for new functions/methods
- [ ] New history object for storing history for input fields to files
